export const OVERDUE_CHARGE_POLICY_V1 = 'DCLA_2026_V1' as const;

export const SUPPORTED_OVERDUE_CHARGE_POLICIES = [
  OVERDUE_CHARGE_POLICY_V1,
] as const;

export type OverdueChargePolicyVersion =
  (typeof SUPPORTED_OVERDUE_CHARGE_POLICIES)[number];

export const NEW_LOAN_OVERDUE_CHARGE_POLICY_VERSION =
  'NEW_LOAN_OVERDUE_CHARGE_POLICY_VERSION';
export const OVERDUE_CHARGE_POLICY_ACTIVATION_DATE =
  'OVERDUE_CHARGE_POLICY_ACTIVATION_DATE';
export const LOAN_CHARGE_SCHEDULER_ENABLED = 'LOAN_CHARGE_SCHEDULER_ENABLED';
export const LOAN_CHARGE_POLL_INTERVAL_MS = 'LOAN_CHARGE_POLL_INTERVAL_MS';
export const LOAN_CHARGE_BATCH_SIZE = 'LOAN_CHARGE_BATCH_SIZE';
